name: CI

on: [push, pull_request]

jobs:
  phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - php-version: 8.0
                      composer-flags: --prefer-stable --prefer-lowest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Setup PHP"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}
            - name: "Install dependencies (lowest dependencies) with composer"
              run: |
                  composer update ${{ matrix.composer-flags }} --no-interaction --no-progress --no-suggest
            - name: "Run tests with phpunit/phpunit"
              run: vendor/bin/phpunit
